### ISSUE TITLE
IOS UI mode in Android

### ISSUE THREAD

**Issue by 08Thug** [alialkorsani/react-native-ui-action-sheet#1]
Consider this as a Query,can we declare IOS UI for android app?.Is there is anyway to call IOS UI in ANDROID?

**Comment by alialkorsani** [comment]
@08Thug sorry for late reply I will make it available soon :)

**Comment by alialkorsani** [comment]
@08Thug now version 1.0.3 available you can add mode="ios" prop to show ios style on android
